# Generated by Django 3.2.16 on 2023-07-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='uploads/', verbose_name='User Image'),
        ),
    ]
