# Generated by Django 3.2.16 on 2023-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='User Image'),
        ),
    ]
