# Generated by Django 3.2.16 on 2023-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads', verbose_name='User Image'),
        ),
    ]
