# Generated by Django 3.2.16 on 2023-11-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='brand',
        ),
    ]
