# Generated by Django 3.2.16 on 2023-11-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_fashion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fashion',
            old_name='Vendor_brand',
            new_name='vendor_brand',
        ),
    ]
