# Generated by Django 3.2.16 on 2023-11-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0005_pastries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Other Images')),
                ('detail', models.TextField(max_length=100, verbose_name='Gadget Details')),
                ('vendor_brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('colour', models.CharField(max_length=20, verbose_name='Colour')),
                ('available_product', models.CharField(max_length=20, verbose_name='Available product')),
                ('delivery_fee', models.CharField(max_length=20, verbose_name='Delivery Fee')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gadgets',
            },
        ),
    ]
